- name: Create jenkins stuff
  hosts: localhost
  roles:
    - create-jobs
  vars:
    folder:
      - 'infrastructure'
    jobs:
      - {'jobName': 'cart-infra', 'repository': 'roboshop-cart-infra','folder':'infrastructure','jenkinsfilename':'Jenkinsfile','branchname':'main'}
      - {'jobName': 'destroy_all', 'repository': 'roboshop-jenkins','folder':'infrastructure','jenkinsfilename':'Jenkinsfile_deleteAll','branchname':'master'}
      - {'jobName': 'transit-gateway-setup', 'repository': 'tf-module-transit','folder':'infrastructure','jenkinsfilename':'Jenkinsfile','branchname':'main'}
      - {'jobName': 'shipping-infra', 'repository': 'roboshop-shipping-infra','folder':'infrastructure','jenkinsfilename':'Jenkinsfile','branchname':'main'}