- name: Create jenkins stuff
  hosts: localhost
  roles:
    - create-jobs
  vars:
    folder:
      - 'infrastructure'
    jobs:
      - {'jobName': 'cart-infra', 'repository': 'roboshop-cart-infra','folder':'infrastructure','jenkinsfilename':'Jenkinsfile'}
      - {'jobName': 'destroy_all', 'repository': 'roboshop-jenkins','folder':'infrastructure','jenkinsfilename':'Jenkinsfile_deleteAll'}