- name: Create jenkins stuff
  hosts: localhost
  ansible.builtin.import_role:
    name: create-jobs
  vars:
    folder:
      - 'demo'
    jobs:
      - {'jobName': 'demo-job', 'repository-name': 'practice-ansible'}