- name: Create jenkins stuff
  hosts: localhost
  roles:
    - create-jobs
  vars:
    folder:
      - 'demo'
    jobs:
      - {'jobName': 'demojob', 'repository': 'practice-ansible','folderName':'demo'}