- name: Copy folder
  template:
    src: jobs.xml
    dest: /tmp/jobs.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/jobs.xml') }}"
    name: "{{item.folder}}/{{item.jobName}}"
    password: admin
    url: http://172.31.80.184:8080
    user: admin