- name: Copy jobs
  template:
    src: jobs.xml
    dest: /tmp/jobs.xml

- community.general.jenkins_job_info:
    name: "{{item.folder}}/{{item.jobName}}"
    user: admin
    password: admin
    url: http://172.31.80.120:8080
  register: my_jenkins_job_info
  ignore_errors: true

- name: Read
  ansible.builtin.debug:
    msg: "{{my_jenkins_job_info.failed}}"

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/jobs.xml') }}"
    name: "{{item.folder}}/{{item.jobName}}"
    password: admin
    url: http://172.31.80.120:8080
    user: admin
  when: my_jenkins_job_info.failed|bool
