- name: Create jenkins folders
  ansible.builtin.include_role:
    name: pipeline-jobs
    tasks_from: folder
  loop: "{{folder}}"

- name: Create jenkins jobs
  ansible.builtin.include_role:
    name: pipeline-jobs
    tasks_from: jobs
  loop: "{{jobs}}"
